dist: xenial
language: python
sudo: true
python:
  - "3.7"

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
      - ubuntu-toolchain-r-test
    packages:
      - llvm-7

before_install:
  - /usr/bin/llc-7 --version
  - /usr/bin/g++ --version

install:
  - pip install -e .[tests]

before_script:
  - mkdir runtime/build && cd runtime/build && cmake .. && cd .. && cmake --build build --target all
  - cd $TRAVIS_BUILD_DIR

script:
  - pytest
