dist: xenial
language: python
sudo: true
python:
  - "3.7"

install:
  - pip install -e .[tests]

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
      - ubuntu-toolchain-r-test
    packages:
      - llvm-7

script:
  # Check versions
  - /usr/bin/llc-7 --version
  - /usr/bin/g++ --version
  # Build runtime library
  - mkdir runtime/build && cd runtime/build && cmake ..
  - cd runtime && cmake --build cmake-build-debug --target all
  # Run pytest
  - pytest
